# Generated by Django 3.1.3 on 2020-11-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=20)),
                ('classid', models.CharField(max_length=20)),
                ('coursename', models.CharField(max_length=30)),
                ('teacherfactor', models.CharField(max_length=30)),
                ('pub_data', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['pub_data'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('uid', models.CharField(max_length=20)),
                ('balance', models.IntegerField(null=True)),
                ('is_vip', models.BooleanField(default=True)),
                ('pub_data', models.DateField(auto_now=True)),
                ('course_message', models.ManyToManyField(blank=True, to='app1.CourseMessage')),
            ],
            options={
                'ordering': ['pub_data'],
            },
        ),
    ]
