# Generated by Django 3.1.3 on 2020-11-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201119_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activates',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
