# Generated by Django 3.1.3 on 2020-11-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201121_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activates',
            field=models.JSONField(default=dict),
        ),
    ]
